# Generated by Django 5.0.6 on 2024-06-26 15:33

import api.profiles_api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=api.profiles_api.models.get_unique_filename)),
            ],
        ),
        migrations.CreateModel(
            name='RoomTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('KITCHEN', 'Kitchen'), ('BATHROOM', 'Bathroom'), ('TOILET', 'Toilet'), ('LAUNDRY', 'Laundry'), ('GARDEN', 'Garden'), ('GARAGE', 'Garage')], default='KITCHEN', max_length=20)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_people', models.PositiveIntegerField(default=0)),
                ('client_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_management.clientnumber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_management.propertytypes')),
                ('room_types', models.ManyToManyField(blank=True, null=True, to='water_management.roomtypes')),
            ],
        ),
    ]
