# Generated by Django 5.0.6 on 2024-08-21 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0002_propertytypes_roomtypes_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermeterreading',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
