# Generated by Django 5.0.6 on 2024-08-30 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0004_consumptionadvice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermeterreading',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
