# Generated by Django 5.0.6 on 2024-06-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_remove_profile_client_number_profile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watermeter',
            name='client_number',
        ),
        migrations.RemoveField(
            model_name='watermeterreading',
            name='water_meter',
        ),
        migrations.RemoveField(
            model_name='watermeterreading',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(default='BG', max_length=5),
        ),
        migrations.DeleteModel(
            name='ClientNumber',
        ),
        migrations.DeleteModel(
            name='WaterMeter',
        ),
        migrations.DeleteModel(
            name='WaterMeterReading',
        ),
    ]
