# Generated by Django 5.0.6 on 2024-08-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_remove_watermeter_client_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='monthly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='push',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekly',
            field=models.BooleanField(default=False),
        ),
    ]
